### ISSUE TITLE
phraseapp: undefined local variable or method `q'

### ISSUE THREAD

**Issue by muller** [phrase/homebrew-brewed#11]
I am getting the following error when trying to `brew tap phrase/brewed`:

```
phraseapp: undefined local variable or method `q' for Formulary::FormulaNamespacea27e7ae251a67d4484b5706e6f8cba52:Module
```

Apparently the following line can be removed:

https://github.com/phrase/homebrew-brewed/blob/42f6baee2fe45f474fc87fd75d9d711942a62743/Formula/phraseapp.rb#L18

**Comment by theSoenke** [comment]
Thanks again for reporting and fixing it!
