### ISSUE TITLE
1.13.0 SHA256 Mismatch

### ISSUE THREAD

**Issue by skreis** [phrase/homebrew-brewed#17]
```
==> Installing phraseapp from phrase/brewed
==> Downloading https://github.com/phrase/phraseapp-client/releases/download/1.13.0/phraseapp_macosx_amd64.tar.gz
==> Downloading from https://github-production-release-asset-2e65be.s3.amazonaws.com/32396643/af69f780-2dec-11e9-816f-1c86ef5d75f3?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Cr
######################################################################## 100.0%
Error: An exception occurred within a child process:
  ChecksumMismatchError: SHA256 mismatch
Expected: dfae709a1271c3747fe7dc622b6ffc0c04c65e46c5980239b2514052a13f8b6b
Actual: 9a20ac632b58263ed1360af46970db8c4b1d5d3e098ebd652c1ee2d8a891ce4c
Archive: /path/to/Homebrew/downloads/008c77f47f8cab538ad510b203aa412c2ecbec32ff65b3db7ab01f4cc6f6fa5f--phraseapp_macosx_amd64.tar.gz
To retry an incomplete download, remove the file above.
```

**Comment by theSoenke** [comment]
@skreis Thanks for reporting it. Now the SHA256 hash should be correct. Currently looking for a way to automate this to prevent something like this in the future

**Comment by skreis** [comment]
@theSoenke thanks!

**Comment by skreis** [comment]
@theSoenke maybe something like pushing a commit to this repo from the phraseapp-client [release script](https://github.com/phrase/phraseapp-client/blob/master/build/release.sh) could help?

**Comment by theSoenke** [comment]
@skreis Yes, that's a good idea. I was also exploring something in that direction

**Comment by jackocnr** [comment]
I'm now getting this for 1.14.2 - any ideas? Also it tells me the latest version of phraseapp cli is actually v1.15.0 but no matter what I try, it only ever downloads 1.14.2.

**Comment by kirchner** [comment]
@jackocnr Thank you for reporting this! The issue should be fixed now.

**Comment by jackocnr** [comment]
Yup that's working now, thanks.

**Comment by vkolosovsky** [comment]
@theSoenke same error for 1.15.1:

==> Upgrading 1 outdated package:
phrase/brewed/phraseapp 1.15.0 -> 1.15.1
==> Upgrading phrase/brewed/phraseapp 
==> Downloading https://github.com/phrase/phraseapp-client/releases/download/1.15.1/phrase
==> Downloading from https://github-production-release-asset-2e65be.s3.amazonaws.com/32396
######################################################################## 100.0%
Error: An exception occurred within a child process:
  ChecksumMismatchError: SHA256 mismatch
Expected: c5ae252333f2afc267ce71bea0ccd4acecd4060484a880a1c3b4a15bc5099c23
  Actual: dee73f13a3f30e13ce111eefbd8b0554b650eb854cbbebb441ff7f762f3efd50

**Comment by theSoenke** [comment]
@vkolosovsky Thanks for reporting it. Now the update to 1.16.0 should work fine
