### ISSUE TITLE
Installing 1.1.12 fails, name mismatch

### ISSUE THREAD

**Issue by lime** [phrase/homebrew-brewed#3]
The current (very recent) version fails to install.

```sh
$ brew upgrade phraseapp
==> Upgrading 1 outdated package, with result:
phrase/brewed/phraseapp 1.1.12
==> Upgrading phrase/brewed/phraseapp
==> Downloading https://github.com/phrase/phraseapp-client/releases/download/1.1.12/phraseapp_macosx_amd64.tar.gz
Already downloaded: /Library/Caches/Homebrew/phraseapp-1.1.12.tar.gz
Error: No such file or directory - phraseapp
```

Apparently the tarball contains a binary called `phraseapp_macosx_amd64` instead of the expected `phraseapp`.

**Comment by sacry-dyn** [comment]
@lime thank you for reporting it. We recently changed how the binaries are build, with the new tap it should work again. Can you confirm this?

**Comment by lime** [comment]
Yeah, with the updated tarball installation succeeds. Thanks!
