### ISSUE TITLE
Is phrase now in homebrew/core or not?

### ISSUE THREAD

**Issue by racer1988** [phrase/homebrew-brewed#42]
I see #38 but then #41 ...

could you explain if the move has been done or not?

**Comment by theSoenke** [comment]
Hi @racer1988, it is in homebrew core and called `phrase-cli` there. There have been some issues as migrating and renaming an formula is currently not supported in brew. To not cause any issues when upgrading an existing installation I've rolled those changes back for now. As a solution we will try to add an alias in the core repo: https://github.com/Homebrew/homebrew-core/pull/121017

Feel free to already upgrade to `phrase-cli` and once there is an automated migration path the reverted migration PR will be merged again.

**Comment by racer1988** [comment]
Thanks for the explanation. 
I will leave the issue open for other to reference, feel free to close if you need, or close it when the new PR will be merged again :)

Thanks Again!

**Comment by theSoenke** [comment]
Thanks for raising this :) I'll then close this once there is a working migration path

**Comment by theSoenke** [comment]
@racer1988 The move should now be successful and running `brew upgrade phrase` switch to the core formula. To avoid any confusion I'll quickly make sure the docs are updated as well
